import {test} from 'node:test';
import assert from 'node:assert/strict';
import {boundedVerifier} from './verifier.mjs';
const binding={requestId:'request',parentId:'parent',region:{x:0,y:0,width:1024,height:1024},files:{source:{sha256:'a'.repeat(64)},candidate:{sha256:'b'.repeat(64)}}};
const proof={requestId:binding.requestId,parentId:binding.parentId,region:binding.region,sourceDigest:binding.files.source.sha256,candidateDigest:binding.files.candidate.sha256,pixelWidth:1024,pixelHeight:1024,expectedRgbaDigest:'c'.repeat(64),expiresAt:Date.now()+10000};
const adapter=fetchImpl=>boundedVerifier({gatewayUrl:'http://owned.internal',nonce:'private-nonce',fetchImpl});
test('HTTP422 is permanent validation without reflecting private worker body',async()=>{const v=adapter(async()=>new Response('private-proof-key',{status:422}));await assert.rejects(v.prepare(binding,'request',new Uint8Array(1),new Uint8Array(1)),{message:'verifier-validation'});});
for(const failure of ['HTTP500','disconnect','invalidJSON','incomplete','oversize','interruptedBody'])test(`${failure} is bounded recoverable stage unavailability`,async()=>{const v=adapter(async()=>{if(failure==='disconnect')throw Error('private-transport-key');if(failure==='HTTP500')return new Response('private-worker-key',{status:500});if(failure==='invalidJSON')return new Response('{private');if(failure==='incomplete')return Response.json({requestId:'request'});if(failure==='oversize')return new Response(' '.repeat(65537));return new Response(new ReadableStream({start(controller){controller.error(Error('private-stream-key'));}}));});await assert.rejects(v.prepare(binding,'request',new Uint8Array(1),new Uint8Array(1)),{message:'verification-unavailable'});});
test('complete bounded PREPARE/FINALIZE and inspect responses retain accepted result',async()=>{const v=adapter(async(_url,options)=>Response.json(options.headers['X-Internal-Stage']==='inspect'?{ok:true}:options.headers['X-Internal-Stage']==='prepare'?proof:{...proof,kind:'verified',outputDigest:'d'.repeat(64),actualRgbaDigest:'c'.repeat(64)}));await v.inspect(new Uint8Array(1));assert.deepEqual(await v.prepare(binding,'request',new Uint8Array(1),new Uint8Array(1)),proof);assert.equal((await v.finalize(binding,'request',proof,new Uint8Array(1))).kind,'verified');});
