import {test} from './browser-fixtures';
import {expect,type Page} from '@playwright/test';
import {claimCharacter,saveInput,openClaimedCharacter,isolatedPartyUrl,expectSaveFeedback} from './overview-helpers';
import {png,pdfFixture} from './handout-fixtures';
async function mount(page:Page,url:string,role:'player'|'dungeon-master',adapter:'local'|'supabase'){
 await page.goto(url);
 await page.evaluate(async({role,adapter,url,key,jwt})=>{
  const base=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();
  const token=crypto.randomUUID(),store=await import('/the-drowned-compass/src/data/local-party-store.ts');await store.writeLocalSession(token,role);
  let content=(await import('/the-drowned-compass/src/data/local-party-content.ts')).localPartyContent(()=>token);
  if(adapter==='supabase'){
   const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');content=(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent(sdk.createClient(url,key,{accessToken:async()=>jwt,auth:{persistSession:false},global:{fetch:(input,init)=>fetch(input,{...init,cache:'no-store'})}}));
  }
  let loads=0,deliveries=0;
  const data={...base,content,getSession:()=>store.readLocalSession(token),getParty:()=>{loads++;return base.getParty();},subscribeToParty:(changed:any)=>base.subscribeToParty(value=>{deliveries++;changed(value);})};
  Object.assign(window,{integrationData:data,integrationCounts:()=>({loads,deliveries})});
  const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js'),renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js'),App=(await import('/the-drowned-compass/src/App.tsx')).App;
  document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:data}));
 },{role,adapter,url:process.env.HANDOUT_LIVE_URL??'',key:process.env.HANDOUT_LIVE_KEY??'',jwt:role==='player'?process.env.HANDOUT_LIVE_PLAYER_JWT??'':process.env.HANDOUT_LIVE_DM_JWT??''});
 await expect(page.getByRole('heading',{name:'The Party',exact:true})).toBeVisible();
}
for(const adapter of ['local','supabase'] as const)test(`${adapter} content + local Character transport: ongoing two-client Character edits survive PDF replacement and calibrated stages`,async({page,context},info)=>{
 test.setTimeout(120_000);test.skip(adapter==='supabase'&&!process.env.HANDOUT_LIVE_URL,'Disposable local backend required');
 const url=isolatedPartyUrl(info),dm=page,player=await context.newPage(),other=await context.newPage();
 await mount(dm,url,'dungeon-master',adapter);await mount(player,url,'player',adapter);await claimCharacter(player);await mount(other,url,'player',adapter);await openClaimedCharacter(other);
 const persistedBefore=await player.evaluate(async()=>{const p=await(window as any).integrationData.getParty();return p.slots.slice(1);});
 await saveInput(player,'Armor Class','17');await expect(other.getByLabel('Armor Class',{exact:true})).toHaveValue('17');
 let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>release=r),accepted=new Promise<void>(r=>ready=r);
 await player.route('**/__drowned_compass_test_party?*',async route=>{if(route.request().method()!=='PATCH')return route.continue();const response=await route.fetch();ready();await held;await route.fulfill({response});});
 const armor=player.getByLabel('Armor Class',{exact:true});await armor.fill('18');await armor.press('Enter');await accepted;await armor.fill('20');await saveInput(other,'Speed (feet)','40');
 await dm.getByRole('button',{name:'Dungeon Master Library',exact:true}).click();
 const title=`${process.env.HANDOUT_FIXTURE_PREFIX??'Integration'} PDF ${adapter} ${info.project.name}`;
 await dm.getByLabel('Title',{exact:true}).fill(title);await dm.getByLabel('File',{exact:true}).setInputFiles({name:'letter.pdf',mimeType:'application/pdf',buffer:pdfFixture()});await dm.getByRole('button',{name:'Save private Handout'}).click();await dm.getByRole('button',{name:new RegExp(title+' Private')}).click();
 const opened=dm.waitForEvent('popup');await dm.getByRole('button',{name:'Open Party Display',exact:true}).click();const display=await opened;
 await dm.getByRole('button',{name:'Reveal and present',exact:true}).click();await expect(display.getByLabel('Party Display page 1')).toBeVisible();
 release();await expect(player.getByRole('alert').filter({hasText:'newer changes'})).toBeVisible();await player.unroute('**/__drowned_compass_test_party?*');await expect(armor).toHaveValue('20');await player.getByRole('alert').filter({hasText:'newer changes'}).getByRole('button',{name:'Retry'}).click();await expectSaveFeedback(player,armor,'Saved');await expect(other.getByLabel('Armor Class',{exact:true})).toHaveValue('20');
 const reader=await context.newPage();await mount(reader,url,'player',adapter);await reader.getByRole('button',{name:'Party Library',exact:true}).click();await reader.getByRole('button',{name:new RegExp(title+' Revealed')}).click();await reader.getByRole('button',{name:'Next page',exact:true}).click();await expect(reader.getByText('Page 2 of 2',{exact:true})).toBeVisible();await expect(display.getByLabel('Party Display page 1')).toBeVisible();
 await dm.getByRole('button',{name:'Display next page'}).click();await expect(display.getByLabel('Party Display page 2')).toBeVisible();await reader.getByRole('button',{name:'Previous page',exact:true}).click();await expect(reader.getByText('Page 1 of 2',{exact:true})).toBeVisible();
 const counts=await player.evaluate(()=>(window as any).integrationCounts());
 await dm.getByLabel('Replacement file').setInputFiles({name:'letter.png',mimeType:'image/png',buffer:png});await dm.getByRole('button',{name:'Replace for everyone'}).click();await expect(reader.getByRole('img',{name:'Handout content',exact:true})).toBeVisible();await expect(dm.getByText('Display page 1 of 1')).toBeVisible();
 await dm.getByRole('button',{name:'Withdraw from Party',exact:true}).click();await expect(display.locator('canvas')).toHaveCount(0);await expect(reader.getByRole('img',{name:'Handout content',exact:true})).toHaveCount(0);
 await dm.getByRole('button',{name:'Back to Party',exact:true}).click();await dm.getByRole('button',{name:'Grid Map editor',exact:true}).click();const mapTitle=title.replace('PDF','map');await dm.getByLabel('Map title').fill(mapTitle);const grid=dm.getByRole('application',{name:'Grid Map drawing surface'});await dm.getByRole('button',{name:'Water',exact:true}).click();await grid.focus();await grid.press('Enter');await dm.getByRole('button',{name:'Save private Grid Map'}).click();await expect(dm.getByRole('status').filter({hasText:'Saved privately'})).toBeVisible();await dm.getByRole('button',{name:'Save as copy (saved version only)'}).click();await expect(dm.getByRole('status').filter({hasText:'Saved private copy'})).toBeVisible();
 await dm.getByRole('button',{name:'Open Dungeon Master Library'}).click();await dm.getByRole('button',{name:'Calibrate physical projection'}).click();await dm.getByLabel('Test square display pixels').fill('72');await dm.getByRole('button',{name:'Confirm measured square'}).click();
 const source=dm.locator('article').filter({has:dm.getByText(mapTitle,{exact:true})}),copy=dm.locator('article').filter({has:dm.getByText(mapTitle+' copy',{exact:true})});await source.getByRole('button',{name:'Reveal and present Grid Map'}).click();await expect(dm.getByRole('button',{name:'Show square / recalibrate'})).toBeEnabled();await expect(display.locator('svg')).toHaveAttribute('data-map-version','2');await dm.getByRole('button',{name:'Pan right',exact:true}).click();await copy.getByRole('button',{name:'Reveal and present Grid Map'}).click();await expect(copy.getByText(/Revealed Grid Map/)).toBeVisible();await expect(dm.getByRole('button',{name:'Show square / recalibrate'})).toBeEnabled();await expect(display.locator('svg')).toHaveAttribute('data-square-pixels','72');await expect(display.locator('svg')).toHaveCSS('transform','matrix(1, 0, 0, 1, 50, 0)');await expect(source.getByText(/Revealed Grid Map/)).toBeVisible();await copy.getByRole('button',{name:'Withdraw Grid Map from Party'}).click();await expect(display.locator('svg')).toHaveCount(0);
 expect(await player.evaluate(()=>(window as any).integrationCounts())).toEqual(counts);
 await saveInput(other,'Armor Class','21');await expect(armor).toHaveValue('21');
 const persisted=await player.evaluate(async()=>await(window as any).integrationData.getParty());expect(persisted.slots[0].character).toMatchObject({armorClass:21,speed:40,fieldVersions:{armorClass:4,speed:1}});expect(persisted.slots.slice(1)).toEqual(persistedBefore);
 await player.reload();await mount(player,url,'player',adapter);await openClaimedCharacter(player);await expect(player.getByLabel('Armor Class',{exact:true})).toHaveValue('21');await expect(player.getByLabel('Speed (feet)',{exact:true})).toHaveValue('40');
 await dm.bringToFront();await dm.screenshot({path:info.outputPath('integrated-library.png'),fullPage:true});await player.bringToFront();await player.screenshot({path:info.outputPath('integrated-character.png'),fullPage:true});expect(await dm.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await display.close();await other.close();await player.close();await reader.close();
});
test('saved-map pending/error feedback is truthful and keyboard recovery works',async({page},info)=>{
 await page.goto('./');await page.evaluate(async()=>{
  const base=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();await base.signIn('dungeon-master','dm-password');let release!:()=>void;const gate=new Promise<void>(r=>release=r);let fail=true;const content={...base.content,listMaps:async()=>{await gate;if(fail)throw new Error('Map connection unavailable; refresh to retry');return [];}};
  Object.assign(window,{releaseMaps:release,recoverMaps:()=>{fail=false;}});const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js'),renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js'),App=(await import('/the-drowned-compass/src/App.tsx')).App;document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:{...base,content}}));
 });await page.getByRole('button',{name:'Dungeon Master Library',exact:true}).click();const maps=page.getByRole('region',{name:'Saved Grid Maps'});await expect(maps.getByRole('status')).toContainText('Loading saved Grid Maps');await expect(maps.getByText('No saved Grid Maps yet.')).toHaveCount(0);await page.evaluate(()=>(window as any).releaseMaps());await expect(maps.getByRole('alert')).toContainText('Map connection unavailable');await expect(maps.getByText('No saved Grid Maps yet.')).toHaveCount(0);await page.evaluate(()=>(window as any).recoverMaps());const refresh=maps.getByRole('button',{name:'Refresh saved maps'});await refresh.focus();await refresh.press('Enter');await expect(maps.getByText('No saved Grid Maps yet.')).toBeVisible();await page.screenshot({path:info.outputPath('loading-recovery.png'),fullPage:true});
});
test('real local backend: pending Character acceptance and conflict survive Handout/map presentation',async({page},info)=>{
 test.skip(!process.env.HANDOUT_LIVE_URL,'Disposable local backend required');await page.goto('./');const opened=page.waitForEvent('popup');
 const running=page.evaluate(async({url,key,jwt,image,pdf,index,prefix})=>{
  const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const auth=sdk.createClient(url,key);await auth.auth.setSession({access_token:jwt,refresh_token:'fixture-refresh'});const factory=(await import('/the-drowned-compass/src/data/supabase-party-data.ts')).createSupabasePartyData,a=factory(url,key),b=factory(url,key);
  const initial=await a.getParty(),slot=initial.slots[index],c=slot.character!;
  let release!:()=>void,accepted:any;const pending=a.updateCharacterOverviewField(slot.id,'armorClass',17,c.fieldVersions.armorClass??0).then(value=>{accepted=value;return new Promise<any>(resolve=>{release=()=>resolve(value);});});
  const until=async(predicate:()=>boolean)=>{for(let i=0;i<500;i++){if(predicate())return;await new Promise(r=>setTimeout(r,10));}throw new Error('Integrated module state did not settle');};await until(()=>!!release);
  const display=(await import('/the-drowned-compass/src/features/presentation/party-display.ts')).createPartyDisplay(a.content,()=>a.getSession());display.openWindow();
  const handout=await a.content.upload({requestId:crypto.randomUUID(),title:prefix+' genuine integration '+index,file:new File([new Uint8Array(pdf)],'letter.pdf',{type:'application/pdf'})});await display.present(handout);
  const independent=await b.updateCharacterOverviewField(slot.id,'speed',40,c.fieldVersions.speed??0),stale=await b.updateCharacterOverviewField(slot.id,'armorClass',19,c.fieldVersions.armorClass??0);
  const current=(await a.content.list()).find(item=>item.id===handout.id)!;const replacement=await a.content.change({id:current.id,expectedVersion:current.version,requestId:crypto.randomUUID(),command:{kind:'replace',file:new File([new Uint8Array(image)],'image.png',{type:'image/png'})}});if(!replacement.ok)throw new Error('Unexpected replacement conflict');
  await a.content.change({id:handout.id,expectedVersion:replacement.item.version,requestId:crypto.randomUUID(),command:{kind:'withdraw'}});await until(()=>!display.getState().selected);
  const domain=await import('/the-drowned-compass/src/domain/grid-map.ts'),editor=domain.createGridMapEditor({columns:8,rows:6});editor.draw('water',[{x:2.5,y:2.5}]);
  const saved=await a.content.saveMap({id:crypto.randomUUID(),expectedVersion:0,requestId:crypto.randomUUID(),title:prefix+' genuine map '+index,document:editor.snapshot().document,background:new File([new Uint8Array(image)],'art.png',{type:'image/png'})});if(!saved.ok)throw new Error('Unexpected create conflict');
  const copy=await a.content.changeMap({id:saved.item.id,expectedVersion:saved.item.version,requestId:crypto.randomUUID(),command:{kind:'copy',id:crypto.randomUUID(),title:prefix+' genuine copy '+index}});if(!copy.ok)throw new Error('Unexpected copy conflict');
  display.calibration({kind:'start',squarePixels:72});display.calibration({kind:'confirm'});await display.presentMap(saved.item);display.viewport({zoom:1,x:50,y:0});await display.presentMap(copy.item);
  release();const first=await pending,final=await b.getParty();Object.assign(window,{realIntegration:{content:a.content,display,copy:copy.item.id}});
  return {first:first.ok,independent:independent.ok,stale:stale.ok,selected:display.getState().selected===copy.item.id,character:final.slots[index].character,unrelated:JSON.stringify(initial.slots.filter((_,i)=>i!==index))===JSON.stringify(final.slots.filter((_,i)=>i!==index)),version:final.slots[index].character!.fieldVersions.armorClass};
 },{url:process.env.HANDOUT_LIVE_URL!,key:process.env.HANDOUT_LIVE_KEY!,jwt:process.env.HANDOUT_LIVE_DM_JWT!,image:Array.from(png),pdf:Array.from(pdfFixture()),index:info.project.name.startsWith('phone')?1:0,prefix:process.env.HANDOUT_FIXTURE_PREFIX!});
 const display=await opened,result=await running;expect(result).toMatchObject({first:true,independent:true,stale:false,selected:true,unrelated:true,version:1,character:{armorClass:17,speed:40}});await expect(display.locator('svg')).toHaveAttribute('data-square-pixels','72');await expect(display.locator('svg')).toHaveCSS('transform','matrix(1, 0, 0, 1, 50, 0)');await display.screenshot({path:info.outputPath('genuine-integrated-display.png')});
 await page.evaluate(async()=>{const {content,copy}=(window as any).realIntegration,item=await content.loadMap(copy);await content.changeMap({id:copy,expectedVersion:item.version,requestId:crypto.randomUUID(),command:{kind:'withdraw'}});});await expect(display.locator('svg')).toHaveCount(0);await display.close();
});
