import { test, expect, type Page } from '@playwright/test';
import { png,pdfFixture } from './handout-fixtures';

async function mountLive(page:Page,role:'dm'|'player') {
 await page.goto('./');
 await page.evaluate(async({url,key,jwt})=>{
  const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const auth=sdk.createClient(url,key);const session=await auth.auth.setSession({access_token:jwt,refresh_token:'local-verification-refresh'});if(session.error)throw session.error;
  const data=(await import('/the-drowned-compass/src/data/supabase-party-data.ts')).createSupabasePartyData(url,key);
  const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js');const renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js');const App=(await import('/the-drowned-compass/src/App.tsx')).App;
  document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:data}));
 },{url:process.env.HANDOUT_LIVE_URL!,key:process.env.HANDOUT_LIVE_KEY!,jwt:role==='dm'?process.env.HANDOUT_LIVE_DM_JWT!:process.env.HANDOUT_LIVE_PLAYER_JWT!});
 await expect(page.getByRole('button',{name:role==='dm'?'Dungeon Master Library':'Party Library',exact:true})).toBeVisible();await page.getByRole('button',{name:role==='dm'?'Dungeon Master Library':'Party Library',exact:true}).click();
}

for(const adapter of ['local','supabase']) test(`${adapter} lifecycle preserves content on failed replace, recovers retry, rejects stale operations and enforces Player visibility`,async({page})=>{
 test.skip(adapter==='supabase'&&!process.env.HANDOUT_LIVE_URL,'Requires local disposable Supabase verifier.');
 await page.goto('./');
 const result=await page.evaluate(async({image,pdf,adapter,url,key,dmJwt,playerJwt})=>{
  let jwt=dmJwt;let data;if(adapter==='local')data=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();else{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});data={content:(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent(client),signIn:async(role:string)=>{jwt=role==='player'?playerJwt:dmJwt;}};}await data.signIn('dungeon-master','dm-password');const original=await data.content.upload({requestId:crypto.randomUUID(),title:'Local lifecycle',file:new File([new Uint8Array(image)],'letter.png',{type:'image/png'})});
  const reveal={id:original.id,expectedVersion:original.version,requestId:crypto.randomUUID(),command:{kind:'reveal'}};const revealed=await data.content.change(reveal);const retried=await data.content.change(reveal);
  let failed=false;try{await data.content.change({id:original.id,expectedVersion:revealed.item.version,requestId:crypto.randomUUID(),command:{kind:'replace',file:new File(['bad'],'bad.png',{type:'image/png'})}});}catch{failed=true;}
  const preserved=(await data.content.open(original.id)).size===image.length;
  const replacement=await data.content.change({id:original.id,expectedVersion:revealed.item.version,requestId:crypto.randomUUID(),command:{kind:'replace',file:new File([new Uint8Array(pdf)],'letter.pdf',{type:'application/pdf'})}});
  const stale=await data.content.change({...reveal,requestId:crypto.randomUUID(),command:{kind:'withdraw'}});
  await data.signIn('player','player-password');const playerList=await data.content.list();const playerBytes=(await data.content.open(original.id,replacement.item.contentVersion)).size;
  let denied=0;for(const command of [{kind:'withdraw'},{kind:'replace',file:new File([new Uint8Array(image)],'letter.png',{type:'image/png'})}])try{await data.content.change({id:original.id,expectedVersion:replacement.item.version,requestId:crypto.randomUUID(),command});}catch{denied++;}
  await data.signIn('dungeon-master','dm-password');const withdrawn=await data.content.change({id:original.id,expectedVersion:replacement.item.version,requestId:crypto.randomUUID(),command:{kind:'withdraw'}});
  const lateRetry=await data.content.change(reveal);const dmBytes=(await data.content.open(original.id)).size;
  await data.signIn('player','player-password');const after=await data.content.list();try{await data.content.open(original.id);}catch{denied++;}
  return {failed,preserved,sameVersion:retried.item.version===revealed.item.version,replacedVisibility:replacement.item.visibility,replacedTitle:replacement.item.title,replacedContentVersion:replacement.item.contentVersion,stale:stale.ok,playerCount:playerList.filter((item:{id:string})=>item.id===original.id).length,playerBytes,denied,afterCount:after.filter((item:{id:string})=>item.id===original.id).length,lateRetry:lateRetry.ok,withdrawnVisibility:withdrawn.item.visibility,dmBytes};
 },{image:Array.from(png),pdf:Array.from(pdfFixture()),adapter,url:process.env.HANDOUT_LIVE_URL??'',key:process.env.HANDOUT_LIVE_KEY??'',dmJwt:process.env.HANDOUT_LIVE_DM_JWT??'',playerJwt:process.env.HANDOUT_LIVE_PLAYER_JWT??''});
 expect(result).toEqual({failed:true,preserved:true,sameVersion:true,replacedVisibility:'revealed',replacedTitle:'Local lifecycle',replacedContentVersion:2,stale:false,playerCount:1,playerBytes:pdfFixture().length,denied:3,afterCount:0,lateRetry:false,withdrawnVisibility:'private',dmBytes:pdfFixture().length});
});

test('two genuine Supabase sessions independently read PDF, receive replacement and clear withdrawal',async({page,browser},info)=>{
 test.skip(!process.env.HANDOUT_LIVE_URL,'Requires local disposable Supabase verifier.');
 const playerContext=await browser.newContext({viewport:info.project.name==='phone'?{width:393,height:851}:{width:1280,height:720}});const player=await playerContext.newPage();
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));player.on('pageerror',error=>errors.push(error.message));
 try{
  await mountLive(page,'dm');await mountLive(player,'player');await page.bringToFront();
  await page.getByLabel('Title',{exact:true}).fill(`Lifecycle ${info.project.name}`);await page.getByLabel('File',{exact:true}).setInputFiles({name:'letter.pdf',mimeType:'application/pdf',buffer:pdfFixture()});await page.getByRole('button',{name:'Save private Handout'}).click();await expect(page.getByRole('main').getByRole('status').filter({hasText:'Saved privately'})).toContainText('Saved privately');
  await expect(player.getByRole('button',{name:new RegExp(`Lifecycle ${info.project.name} Revealed`)})).toHaveCount(0);
  await page.getByRole('button',{name:new RegExp(`Lifecycle ${info.project.name} Private`)}).click();await page.getByRole('button',{name:'Reveal to Party',exact:true}).click();await expect(page.getByRole('main').getByRole('status').filter({hasText:'Revealed'})).toContainText('Revealed');
  await expect(player.getByRole('button',{name:new RegExp(`Lifecycle ${info.project.name} Revealed`)})).toBeVisible();await player.getByRole('button',{name:new RegExp(`Lifecycle ${info.project.name} Revealed`)}).click();await expect(player.getByText('Page 1 of 2')).toBeVisible();await player.getByRole('button',{name:'Next page'}).click();await expect(player.getByText('Page 2 of 2')).toBeVisible();
  await page.getByRole('button',{name:'Next page'}).click();await page.getByRole('button',{name:'Previous page'}).click();await expect(player.getByText('Page 2 of 2')).toBeVisible();
  const download=player.waitForEvent('download');await player.getByRole('link',{name:'Download Handout'}).click();expect((await download).suggestedFilename()).toContain('.pdf');
  await page.bringToFront();await page.getByLabel('Replacement file').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('bad')});await page.getByRole('button',{name:'Replace for everyone'}).click();await expect(page.getByRole('alert')).toContainText('image contents');await expect(player.getByText('Page 2 of 2')).toBeVisible();
  await page.getByLabel('Replacement file').setInputFiles({name:'map.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'Replace for everyone'}).click();await expect(page.getByRole('main').getByRole('status').filter({hasText:'Replacement saved'})).toContainText('Replacement saved');await expect(player.getByRole('img',{name:'Handout content'})).toBeVisible();await expect(player.getByText('Page 2 of 2')).toHaveCount(0);await expect(player.getByRole('heading',{name:`Lifecycle ${info.project.name}`})).toBeVisible();
  await player.screenshot({path: info.outputPath('handout-lifecycle.spec.png'),fullPage:true});
  await page.bringToFront();await page.getByRole('button',{name:'Withdraw from Party'}).click();await expect(player.getByRole('heading',{name:`Lifecycle ${info.project.name}`})).toHaveCount(0);await expect(player.getByRole('img',{name:'Handout content'})).toHaveCount(0);await expect(player.getByText('This Handout is no longer available in your Library.')).toBeVisible();
  await page.getByRole('button',{name:'Reveal to Party'}).click();await expect(player.getByRole('button',{name:new RegExp(`Lifecycle ${info.project.name} Revealed`)})).toBeVisible();
  await player.reload();await mountLive(player,'player');await expect(player.getByRole('button',{name:new RegExp(`Lifecycle ${info.project.name} Revealed`)})).toBeVisible();
  expect(errors).toEqual([]);expect(await player.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await playerContext.close();}
});

test('ambiguous replacement retry keeps original intent after subscription advances and reports later conflict',async({page},info)=>{
 test.skip(!process.env.HANDOUT_LIVE_URL,'Requires local disposable Supabase verifier.');await mountLive(page,'dm');
 const title=`Lifecycle retry ${info.project.name}`;await page.getByLabel('Title',{exact:true}).fill(title);await page.getByLabel('File',{exact:true}).setInputFiles({name:'first.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'Save private Handout'}).click();await expect(page.getByRole('main').getByRole('status').filter({hasText:'Saved privately'})).toContainText('Saved privately');await page.getByRole('button',{name:new RegExp(`${title} Private`)}).click();await page.getByRole('button',{name:'Reveal to Party'}).click();await expect(page.getByRole('main').getByRole('status').filter({hasText:'Revealed'})).toContainText('Revealed');
 let loseCommit=true,loseRead=false;
 await page.route('**/rest/v1/rpc/change_party_handout',async route=>{const response=await route.fetch();if(loseCommit){loseCommit=false;loseRead=true;await route.fulfill({status:400,json:{code:'VERIFY_LOST_RESPONSE',message:'Simulated unavailable commit response'}});}else await route.fulfill({response});});
 await page.route('**/rest/v1/party_handouts?**',async route=>{if(loseRead&&route.request().url().includes('id=eq.')){await route.fulfill({status:400,json:{code:'VERIFY_UNAVAILABLE',message:'Simulated unavailable reconciliation'}});}else await route.continue();});
 const initial=await current();
 await page.getByLabel('Replacement file').setInputFiles({name:'next.pdf',mimeType:'application/pdf',buffer:pdfFixture()});await page.getByRole('button',{name:'Replace for everyone'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'Replace for everyone'})).toBeEnabled();loseRead=false;await page.getByRole('button',{name:'Retry opening Handout'}).evaluateAll(buttons=>buttons.forEach(button=>(button as HTMLButtonElement).click()));await expect(page.getByText('Page 1 of 2')).toBeVisible();
 async function current(){return page.evaluate(async({url,key,jwt,title})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const row=await client.from('party_handouts').select('id,party_id,object_id,version,visibility,content_version').eq('title',title).single();if(row.error)throw row.error;return row.data;},{url:process.env.HANDOUT_LIVE_URL!,key:process.env.HANDOUT_LIVE_KEY!,jwt:process.env.HANDOUT_LIVE_DM_JWT!,title});}
 const committed=await current();expect(committed.version).toBe(3);
 await page.getByRole('button',{name:'Replace for everyone'}).click();await expect(page.getByRole('main').getByRole('status').filter({hasText:'Replacement saved'})).toContainText('Replacement saved');expect((await current()).version).toBe(3);
 const obsolete=await page.evaluate(async({url,key,jwt,path})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});return Boolean((await client.storage.from('party-handouts').download(path)).error);},{url:process.env.HANDOUT_LIVE_URL!,key:process.env.HANDOUT_LIVE_KEY!,jwt:process.env.HANDOUT_LIVE_DM_JWT!,path:`${initial.party_id}/${initial.object_id}`});expect(obsolete).toBe(true);
 loseCommit=true;await page.getByLabel('Replacement file').setInputFiles({name:'third.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'Replace for everyone'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'Replace for everyone'})).toBeEnabled();loseRead=false;await page.getByRole('button',{name:'Retry opening Handout'}).evaluateAll(buttons=>buttons.forEach(button=>(button as HTMLButtonElement).click()));await expect(page.getByRole('img',{name:'Handout content'})).toBeVisible();
 const latest=await current();expect(latest.version).toBe(4);
 await page.evaluate(async({url,key,jwt,id,version})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const result=await client.rpc('change_party_handout',{p_id:id,p_expected_version:version,p_request_id:crypto.randomUUID(),p_kind:'withdraw'});if(result.error)throw result.error;},{url:process.env.HANDOUT_LIVE_URL!,key:process.env.HANDOUT_LIVE_KEY!,jwt:process.env.HANDOUT_LIVE_DM_JWT!,id:latest.id,version:latest.version});
 await expect(page.getByRole('button',{name:'Replace private Handout'})).toBeVisible();await page.getByRole('button',{name:'Replace private Handout'}).click();await expect(page.getByRole('alert')).toContainText('changed elsewhere');await expect(page.getByLabel('Replacement file')).toHaveValue(/third.png/);const after=await current();expect(after.version).toBe(5);expect(after.visibility).toBe('private');
 const cleanup=await page.evaluate(async({url,key,jwt,old,current})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});return {oldGone:Boolean((await client.storage.from('party-handouts').download(old)).error),currentUsable:!(await client.storage.from('party-handouts').download(current)).error};},{url:process.env.HANDOUT_LIVE_URL!,key:process.env.HANDOUT_LIVE_KEY!,jwt:process.env.HANDOUT_LIVE_DM_JWT!,old:`${committed.party_id}/${committed.object_id}`,current:`${after.party_id}/${after.object_id}`});expect(cleanup).toEqual({oldGone:true,currentUsable:true});
});
