import {test,expect,type Page} from '@playwright/test';
import {randomUUID,createHash} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {sql,localSettings} from '../scripts/local-verification.mjs';
import {crc,decode} from '../supabase/functions/map-generation/verifier/png.mjs';
function chunk(name:string,body:Buffer){const b=Buffer.alloc(body.length+12);b.writeUInt32BE(body.length);b.write(name,4);b.set(body,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
function image(stage=false){const header=Buffer.alloc(13);header.writeUInt32BE(1024);header.writeUInt32BE(1024,4);header[8]=8;header[9]=6;const raw=Buffer.alloc(1024*(4096+1));for(let y=0;y<1024;y++)for(let x=0;x<1024;x++){const i=y*4097+1+x*4;raw[i]=stage&&x>=512&&y>=512?40:190;raw[i+1]=stage&&x>=512&&y>=512?180:40;raw[i+2]=50;raw[i+3]=255;}return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);}
// Explicit privileged fixture of the already accepted04/08 registration contract.
// This does not execute generation, verification workers or a live provider.
async function stage(party:string,parent:any,constrained:boolean,bytes:Buffer){
 const settings=localSettings(),id=randomUUID();const r=await fetch(settings.API_URL+'/storage/v1/object/party-handouts/'+party+'/'+id,{method:'POST',headers:{apikey:settings.SERVICE_ROLE_KEY,Authorization:'Bearer '+settings.SERVICE_ROLE_KEY,'Content-Type':'image/png'},body:bytes});expect(r.ok).toBe(true);
 const row=JSON.parse(sql(`select to_jsonb(v) from public.party_map_artwork_versions v where id='${parent.id}';`));
 const background={...row.background,object_id:id,digest:createHash('sha256').update(bytes).digest('hex'),size:bytes.length};
 const out=await fetch(settings.API_URL+'/rest/v1/rpc/attach_server_map_artwork_version',{method:'POST',headers:{apikey:settings.SERVICE_ROLE_KEY,Authorization:'Bearer '+settings.SERVICE_ROLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({p_party:party,p_family:parent.familyId,p_parent:parent.id,p_expected_version:JSON.parse(sql(`select version from public.party_grid_maps where id='${parent.familyId}';`)),p_request:id,p_job:id,p_origin:constrained?'revised':'generated',p_title:'Ticket11 '+(constrained?'aligned revision':'fresh whole generation'),p_document:row.document,p_background:background,p_reference:null,p_instructions:'Explicit privileged fixture; provider disabled',p_constrained:constrained})});expect(out.ok).toBe(true);return id;
}
async function mount(page:Page,index:number){await page.goto('./');await page.evaluate(async({url,key,jwt,bytes})=>{
 const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const content=(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent(client);
 const session=async()=>{const r=await client.from('party_members').select('role');if(r.error)throw r.error;return r.data.some((m:any)=>m.role==='dungeon-master')?{role:'dungeon-master'}:null;};
 const display=(await import('/the-drowned-compass/src/features/presentation/party-display.ts')).createPartyDisplay(content,session);
 const created=await content.attachMapVersion({familyId:crypto.randomUUID(),expectedVersion:0,requestId:crypto.randomUUID(),title:'Ticket11 source',document:{columns:4,rows:4,feetPerSquare:5,terrain:[],edges:[]},artwork:new File([new Uint8Array(bytes)],'source.png',{type:'image/png'}),placement:{x:0,y:0,width:4,height:4}});if(!created.ok)throw Error('Fixture conflict');
 const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js');const renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js');const Workshop=(await import('/the-drowned-compass/src/features/grid-map/GridMapWorkshop.tsx')).GridMapWorkshop;const Controls=(await import('/the-drowned-compass/src/features/presentation/DisplayControls.tsx')).DisplayControls;
 document.body.replaceChildren();const root=document.createElement('div');document.body.append(root);const h=React.createElement??React.default.createElement;(renderer.createRoot??renderer.default.createRoot)(root).render(h(React.Fragment??React.default.Fragment,null,h(Workshop,{active:true,content,mapId:created.version.familyId,onBack:()=>{},onLibrary:()=>{},onUseMap:(v:any)=>display.presentMap(v)}),h(Controls,{display})));
 Object.assign(window,{stages:{content,client,display,parent:created.version}});
 },{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,jwt:JSON.parse(process.env.MAP_DISPLAY_DM_JWTS!)[index],bytes:[...image()]});}
test.beforeEach(async({page})=>{page.on('response',async r=>{if(r.status()>=400){let code='';try{code=(await r.json()).code??'';}catch{}console.log(JSON.stringify({event:'http-error',path:new URL(r.url()).pathname,status:r.status(),code}));}});});
const pixels=(popup:Page,x:number,y:number)=>popup.locator('canvas').evaluate((c:HTMLCanvasElement,{x,y})=>[...c.getContext('2d')!.getImageData(Math.floor(c.width*x),Math.floor(c.height*y),1,1).data],{x,y});
test('genuine authority aligned stages retain calibration/mask; older branch and explicit incompatible hidden setup',async({page,isMobile},info)=>{
 test.skip(!process.env.MAP_LIVE_URL,'Requires owned local authority fixtures');const index=info.project.name==='phone'?1:0;await mount(page,index);const parent=await page.evaluate(()=>(window as any).stages.parent);const owned=JSON.parse(process.env.MAP_DISPLAY_OWNED!)[index];
 const original=await decode(image()),later=await decode(image(true));let outside=0,mismatches=0;for(let y=0;y<1024;y++)for(let x=0;x<1024;x++)if(x<512||y<512){outside++;const p=(y*1024+x)*4;for(let c=0;c<4;c++)if(original[p+c]!==later[p+c])mismatches++;}expect(mismatches).toBe(0);console.log(`Ticket11 privileged fixture exact outside pixels: ${outside}; no generation/provider claim`);
 const aligned=await stage(owned.party,parent,true,image(true));const fresh=await stage(owned.party,parent,false,image(true));
 await expect(page.getByRole('button',{name:/Inspect version 3/})).toBeVisible();await page.getByRole('button',{name:/Inspect version 1/}).click();
 const opening=page.waitForEvent('popup');await page.getByRole('button',{name:'Use this map',exact:true}).click();let popup=await opening;await expect(popup.locator('canvas')).toBeVisible();expect(await pixels(popup,.6,.6)).toEqual([0,0,0,255]);
 await page.getByRole('button',{name:'Calibrate physical projection'}).click();await page.getByLabel('Test square display pixels').fill('73');await page.getByRole('button',{name:'Confirm measured square'}).click();await page.getByRole('button',{name:'Pan right',exact:true}).click();await page.getByRole('button',{name:'Pan down',exact:true}).click();
 const brush=page.getByLabel('Private reveal brush canvas');await brush.scrollIntoViewIfNeeded();const point=await brush.evaluate((s:SVGSVGElement)=>{const p=new DOMPoint(.5,.5).matrixTransform(s.getScreenCTM()!);return{x:p.x,y:p.y};});if(isMobile)await page.touchscreen.tap(point.x,point.y);else await page.mouse.click(point.x,point.y);
 await expect.poll(()=>page.evaluate(()=>(window as any).stages.display.getState().reveal.status)).toBe('accepted');await expect.poll(()=>pixels(popup,.1,.1)).not.toEqual([0,0,0,255]);const accepted=await page.evaluate(()=>(window as any).stages.content.readMapWorkspace());
 await page.getByRole('button',{name:/Inspect version 2/}).click();await expect(page.getByLabel('Saved stage identities')).toContainText(parent.id);await page.getByRole('button',{name:'Use this map',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).stages.display.getState().presentation.version.id)).toBe(aligned);
 const state=await page.evaluate(()=>(window as any).stages.display.getState());expect({square:state.squarePixels,x:state.x,y:state.y,mode:state.mode,mask:state.presentation.mask}).toEqual({square:73,x:50,y:50,mode:'calibrated',mask:accepted.presentation.mask});await expect(popup.locator('canvas')).toHaveCSS('width','292px');await expect(popup.locator('canvas')).toHaveCSS('transform','matrix(1, 0, 0, 1, 50, 50)');expect(await pixels(popup,.6,.6)).toEqual([0,0,0,255]);
 // Older-parent branching through the existing accepted attachment command never presents.
 const branch=await page.evaluate(async()=>{const w=(window as any).stages,workspace=await w.content.readMapWorkspace();return w.content.attachMapVersion({familyId:w.parent.familyId,parentVersionId:w.parent.id,expectedVersion:workspace.families.find((f:any)=>f.id===w.parent.familyId).version,requestId:crypto.randomUUID(),title:'Ticket11 older-parent branch'});});expect(branch.ok).toBe(true);expect(branch.version.parentVersionId).toBe(parent.id);expect((await page.evaluate(()=>(window as any).stages.content.readMapWorkspace())).presentation.version.id).toBe(aligned);
 await page.getByRole('button',{name:/Inspect version 4/}).click();await expect(page.getByLabel('Saved stage identities')).toContainText(branch.version.id);await expect(page.getByLabel('Saved stage identities')).toContainText(aligned);
 await page.getByRole('button',{name:/Inspect version 1/}).click();await page.getByRole('button',{name:'Use this map',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).stages.display.getState().presentation.version.id)).toBe(parent.id);expect(await pixels(popup,.6,.6)).toEqual([0,0,0,255]);
 await page.getByRole('button',{name:/Inspect version 3/}).click();page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Use this map',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Current display retained'})).toBeVisible();expect((await page.evaluate(()=>(window as any).stages.content.readMapWorkspace())).presentation.version.id).toBe(parent.id);expect(await pixels(popup,.1,.1)).not.toEqual([0,0,0,255]);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Use this map',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).stages.display.getState().presentation.version.id)).toBe(fresh);await expect.poll(async()=>popup.locator('canvas').getAttribute('data-presentation-revision')).toBe(String((await page.evaluate(()=>(window as any).stages.display.getState())).presentation.revision));expect(await pixels(popup,.1,.1)).toEqual([0,0,0,255]);expect(await pixels(popup,.6,.6)).toEqual([0,0,0,255]);await expect(page.getByRole('button',{name:'Uncover whole map',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Clear display',exact:true}).click();await expect(popup.locator('canvas')).toHaveCount(0);await page.getByRole('button',{name:'Use this map',exact:true}).click();await expect(popup.locator('canvas')).toBeVisible();await expect(page.getByRole('button',{name:'Uncover whole map',exact:true})).toBeDisabled();
 await page.evaluate(async()=>{const d=(window as any).stages.display;d.calibration({kind:'reset'});d.reveal({type:'uncover-all',confirmed:true});await d.saveReveal();});expect((await page.evaluate(()=>(window as any).stages.display.getState())).presentation.mask.uncovered).toEqual([]);await page.getByRole('button',{name:'Confirm measured square'}).click();await expect(page.getByRole('button',{name:'Uncover whole map',exact:true})).toBeEnabled();
 expect(await popup.locator('body').innerHTML()).not.toMatch(/href|<img|<image|secret|prompt|button|input|data:image/i);
 await popup.close();await expect(page.getByRole('button',{name:'Open Party Display',exact:true})).toBeVisible();const reopen=page.waitForEvent('popup');await page.getByRole('button',{name:'Open Party Display',exact:true}).click();popup=await reopen;await expect(popup.locator('canvas')).toBeVisible();expect(await pixels(popup,.6,.6)).toEqual([0,0,0,255]);
 const denials=await page.evaluate(async({url,key,jwts,dmJwt,party,ids,objects})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const factory=(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent;const results=[];for(const object of objects){const r=await fetch(url+'/storage/v1/object/authenticated/party-handouts/'+party+'/'+object,{cache:'no-store',headers:{apikey:key,Authorization:'Bearer '+dmJwt}});if(!r.ok)throw Error('Known owned object was not readable by DM');}for(const jwt of jwts){let denied=0;const content=factory(sdk.createClient(url,key,{accessToken:async()=>jwt}));for(const [n,id] of ids.entries()){try{await content.openMapVersion(id);}catch{denied++;}const r=await fetch(url+'/storage/v1/object/authenticated/party-handouts/'+party+'/'+objects[n],{cache:'no-store',headers:{apikey:key,Authorization:'Bearer '+(jwt??key)}});if(!r.ok)denied++;}results.push(denied);}return results;},{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,jwts:[JSON.parse(process.env.MAP_DISPLAY_PLAYER_JWTS!)[index],JSON.parse(process.env.MAP_DISPLAY_EXPIRED_DM_JWTS!)[index],null],dmJwt:JSON.parse(process.env.MAP_DISPLAY_DM_JWTS!)[index],party:owned.party,ids:[parent.id,aligned,fresh],objects:JSON.parse(sql(`select jsonb_agg(background->>'object_id' order by n) from unnest(array['${parent.id}','${aligned}','${fresh}']) with ordinality as wanted(id,n) join public.party_map_artwork_versions v using(id);`))});expect(denials).toEqual([6,6,6]);
 // Different family with identical drawing geometry must also demand acknowledgement.
 await page.evaluate(async()=>{const w=(window as any).stages,version=await w.content.attachMapVersion({familyId:crypto.randomUUID(),expectedVersion:0,requestId:crypto.randomUUID(),title:'Ticket11 foreign drawing',document:w.parent.document});await w.display.presentMap(version.version,true);});
 await expect.poll(()=>page.evaluate(()=>(window as any).stages.display.getState().registrationChanged)).toBe(true);
 await page.getByRole('button',{name:'Confirm measured square'}).click();
 await page.getByRole('button',{name:'Clear display',exact:true}).click();await expect(popup.locator('canvas')).toHaveCount(0);
 await page.evaluate(async()=>{const w=(window as any).stages;await w.display.presentMap(w.parent,true);});await expect(popup.locator('canvas')).toBeVisible();
 sql(`delete from public.party_members where party_id='${owned.party}' and user_id='${owned.dm}';`);await expect(popup.locator('canvas,svg')).toHaveCount(0);await page.evaluate(()=>(window as any).stages.display.dispose());
});
