import {test} from './browser-fixtures';
import {expect} from '@playwright/test';
import {png,pdfFixture} from './handout-fixtures';
test('compiled normal entry uploads PDF, displays and copies calibrated maps',async({page,context},info)=>{
 const runtimeErrors:string[]=[],sources:string[]=[];page.on('pageerror',e=>runtimeErrors.push(e.message));context.on('request',r=>{if(new URL(r.url()).pathname.includes('/src/')||r.url().includes('__drowned_compass_test'))sources.push(r.url());});
 await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
 await page.goto('./');await page.getByRole('button',{name:/^Dungeon Master /}).click();await page.getByLabel('Shared password').fill('dm-password');await page.getByRole('button',{name:'Enter the Party'}).click();await page.getByRole('button',{name:'Dungeon Master Library',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Compiled PDF');await page.getByLabel('File',{exact:true}).setInputFiles({name:'letter.pdf',mimeType:'application/pdf',buffer:pdfFixture()});await page.getByRole('button',{name:'Save private Handout'}).click();await expect(page.getByLabel('PDF first page preview')).toBeVisible();await page.getByRole('button',{name:/Compiled PDF Private/}).click();
 const open=page.waitForEvent('popup');await page.getByRole('button',{name:'Open Party Display',exact:true}).click();const display=await open;display.on('pageerror',e=>runtimeErrors.push(e.message));await page.getByRole('button',{name:'Reveal and present',exact:true}).click();await expect(display.getByLabel('Party Display page 1')).toBeVisible();await page.getByRole('button',{name:'Display next page'}).click();await expect(display.getByLabel('Party Display page 2')).toBeVisible();
 await page.getByRole('button',{name:'Back to Party',exact:true}).click();await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();await page.getByLabel('Map title').fill('Compiled map');await page.getByLabel('Map Background',{exact:true}).setInputFiles({name:'art.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toBeVisible();await page.getByRole('button',{name:'Save as copy (saved version only)'}).click();await expect(page.getByRole('status').filter({hasText:'Saved private copy'})).toBeVisible();await page.getByRole('button',{name:'Open Dungeon Master Library'}).click();
 await page.getByRole('button',{name:'Calibrate physical projection'}).click();await page.getByLabel('Test square display pixels').fill('72');await page.getByRole('button',{name:'Confirm measured square'}).click();const source=page.locator('article').filter({has:page.getByText('Compiled map',{exact:true})}),copy=page.locator('article').filter({has:page.getByText('Compiled map copy',{exact:true})});await source.getByRole('button',{name:'Reveal and present Grid Map'}).click();await expect(page.getByRole('button',{name:'Show square / recalibrate'})).toBeEnabled();await expect(display.locator('svg')).toHaveAttribute('data-map-version','2');await page.getByRole('button',{name:'Pan right',exact:true}).click();await copy.getByRole('button',{name:'Reveal and present Grid Map'}).click();await expect(copy.getByText(/Revealed Grid Map/)).toBeVisible();await expect(page.getByRole('button',{name:'Show square / recalibrate'})).toBeEnabled();await expect(display.locator('svg')).toHaveAttribute('data-square-pixels','72');await expect(display.locator('svg')).toHaveCSS('transform','matrix(1, 0, 0, 1, 50, 0)');await copy.getByRole('button',{name:'Withdraw Grid Map from Party'}).click();await expect(display.locator('svg')).toHaveCount(0);
 await page.screenshot({path:info.outputPath('compiled-library.png'),fullPage:true});expect(runtimeErrors).toEqual([]);expect(sources).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await display.close();
});
