import {test,expect,type Page} from '@playwright/test';
const demo='./.scratch/party-presentation/verification/ticket07/demo.html';
async function open(page:Page){const created=page.waitForEvent('popup');await page.getByRole('button',{name:'Open Party Display',exact:true}).click();return created;}
async function setup(page:Page){await page.goto(demo);return open(page);}
async function state(page:Page){return page.evaluate(()=>(window as any).projectionDemo.display.getState());}
async function cell(display:Page){return Number(await display.locator('svg').getAttribute('data-square-pixels'));}
test('normal app offers measured blank square without revealing private saved maps',async({page})=>{
 await page.goto('./');await page.getByRole('button',{name:/^Dungeon Master /}).click();await page.getByLabel('Shared password').fill('dm-password');await page.getByRole('button',{name:'Enter the Party'}).click();await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();await page.getByLabel('Map title').fill('Private map stays private');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toBeVisible();await page.getByRole('button',{name:'Dungeon Master Library',exact:true}).click();const display=await open(page);await page.getByRole('button',{name:'Calibrate physical projection'}).click();await expect(display.getByLabel('Physical calibration test square')).toBeVisible();await page.getByLabel('Test square display pixels').fill('80');await expect.poll(()=>display.locator('svg').evaluate(el=>el.getBoundingClientRect().width)).toBe(80);await page.getByRole('button',{name:'Confirm measured square'}).click();await expect(page.getByLabel('Display zoom')).toBeDisabled();await expect(page.getByRole('button',{name:'Fit to screen',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Present saved Grid Map'})).toHaveCount(0);await expect(display.locator('button,input,a')).toHaveCount(0);await expect(display.locator('body')).toHaveText('');
});
test('measured cell size and pan survive saved content grid viewport and reopened popup',async({page},info)=>{
 const display=await setup(page);await page.getByRole('button',{name:'Calibrate physical projection'}).click();await page.getByLabel('Test square display pixels').fill('72');await page.getByRole('button',{name:'Confirm measured square'}).click();await page.getByRole('button',{name:'Demo saved map 1',exact:true}).click();await expect(display.getByLabel('Saved Grid Map on Party Display')).toBeVisible();expect(await cell(display)).toBe(72);await expect.poll(()=>display.locator('[data-terrain=water]').first().evaluate(el=>el.getBoundingClientRect().width)).toBe(72);await expect.poll(()=>display.locator('image').evaluate(el=>{const box=el.getBoundingClientRect();return box.width/box.height;})).toBe(2);await expect(display.locator('image')).toHaveAttribute('width','12');await expect(display.locator('[data-terrain=water]')).toHaveCount(4);await page.getByRole('button',{name:'Pan right',exact:true}).click();await page.getByRole('button',{name:'Pan down',exact:true}).click();await expect(display.locator('svg')).toHaveCSS('transform','matrix(1, 0, 0, 1, 50, 50)');
 await page.evaluate(()=>{const d=(window as any).projectionDemo.display;d.fit();d.viewport({zoom:4,x:999,y:999});});expect((await state(page)).zoom).toBe(1);expect((await state(page)).x).toBe(50);
 for(const index of [2,3,1]){await page.getByRole('button',{name:`Demo saved map ${index}`,exact:true}).click();await expect(display.locator('svg')).toHaveAttribute('data-square-pixels','72');await expect(display.locator('svg')).toHaveCSS('transform','matrix(1, 0, 0, 1, 50, 50)');}
 await display.setViewportSize({width:1000,height:600});await expect(page.getByRole('alert')).toContainText('viewport changed');expect(await cell(display)).toBe(72);await page.getByRole('button',{name:'Confirm measured square'}).click();await expect(page.getByRole('alert')).toHaveCount(0);
 await display.close();await expect(page.getByRole('button',{name:'Open Party Display',exact:true})).toBeVisible();const reopened=await open(page);await expect(reopened.locator('svg')).toHaveAttribute('data-square-pixels','72');await expect(reopened.locator('svg')).toHaveCSS('transform','matrix(1, 0, 0, 1, 50, 50)');
 await page.screenshot({path:`/private/tmp/ticket07-implementer-${info.project.name}-controls.png`,fullPage:true});await reopened.screenshot({path:`/private/tmp/ticket07-implementer-${info.project.name}-display.png`});
 await page.getByRole('button',{name:'Reset calibration / ordinary viewing'}).click();await expect(page.getByLabel('Display zoom')).toBeEnabled();await page.getByRole('button',{name:'Fit to screen',exact:true}).click();await expect.poll(()=>cell(reopened)).not.toBe(72);await expect(reopened.locator('button,input,a')).toHaveCount(0);
});
test('saved updates refresh but unsaved drawing never enters projection; withdrawal and authority clear',async({page})=>{
 const display=await setup(page);await page.getByRole('button',{name:'Demo saved map 1',exact:true}).click();await expect(display.locator('svg')).toBeVisible();await page.evaluate(async()=>{const w=(window as any).projectionDemo;const domain=await import('/the-drowned-compass/src/domain/grid-map.ts');const editor=domain.createGridMapEditor(w.maps[0].document);editor.draw('difficult',[{x:9.5,y:4.5}]);w.unsavedDocument=editor.snapshot().document;});await expect(display.locator('[data-terrain=difficult]')).toHaveCount(0);
 await page.evaluate(()=>{const w=(window as any).projectionDemo;w.maps[0]={...w.maps[0],version:2,document:w.unsavedDocument};window.dispatchEvent(new Event('drowned-compass-content-changed'));});await expect(display.locator('svg')).toHaveAttribute('data-map-version','2');await expect(display.locator('[data-terrain=difficult]')).toHaveCount(1);
 await page.evaluate(()=>{const w=(window as any).projectionDemo;w.maps[0]={...w.maps[0],visibility:'private'};window.dispatchEvent(new Event('drowned-compass-content-changed'));});await expect(display.locator('svg')).toHaveCount(0);await page.getByRole('button',{name:'Demo saved map 1',exact:true}).click();await expect(display.locator('svg')).toHaveCount(0);await expect(page.getByRole('status')).toContainText('private');await page.getByRole('button',{name:'Demo saved map 2',exact:true}).click();await expect(display.locator('svg')).toBeVisible();await page.evaluate(()=>(window as any).projectionDemo.data.signOut());await expect(display.locator('svg')).toHaveCount(0);
});
test('late background reads cannot reveal withdrawal or overwrite a newer selection; current-version retry succeeds',async({page})=>{
 const display=await setup(page);await page.evaluate(()=>{const w=(window as any).projectionDemo;const original=w.content.openMapBackground;w.originalBackground=original;w.content.openMapBackground=async(...args:any[])=>{await new Promise(resolve=>w.releaseBackground=resolve);return original(...args);};w.pending=w.display.presentMap(w.maps[0].id);});await expect.poll(()=>page.evaluate(()=>!!(window as any).projectionDemo.releaseBackground)).toBe(true);
 await page.evaluate(async()=>{const w=(window as any).projectionDemo;w.maps[0]={...w.maps[0],visibility:'private'};w.releaseBackground();await w.pending;});await expect(display.locator('svg')).toHaveCount(0);
 await page.evaluate(async()=>{const w=(window as any).projectionDemo;w.maps[0]={...w.maps[0],visibility:'revealed'};w.pending=w.display.presentMap(w.maps[0].id);});await page.evaluate(async()=>{const w=(window as any).projectionDemo;w.display.clear();w.content.openMapBackground=w.originalBackground;await w.display.presentMap(w.maps[2].id);w.releaseBackground();await w.pending;});await expect(display.locator('svg')).toHaveAttribute('viewBox','0 0 18 10');
 await page.evaluate(async()=>{const w=(window as any).projectionDemo;let raced=false;w.content.openMapBackground=async()=>{if(!raced){raced=true;w.maps[0]={...w.maps[0],version:3};}return w.originalBackground();};await w.display.presentMap(w.maps[0].id);});await expect(display.locator('svg')).toHaveAttribute('data-map-version','3');
});
test('reopened display waits for current access and invalid square values leave settings intact',async({page})=>{
 const display=await setup(page);await page.getByRole('button',{name:'Demo saved map 1',exact:true}).click();await expect(display.locator('svg')).toBeVisible();await display.close();await page.evaluate(()=>{const w=(window as any).projectionDemo;w.content.listMaps=async()=>{await new Promise(resolve=>w.releaseList=resolve);return w.maps;};});const reopened=await open(page);await reopened.evaluate(()=>window.dispatchEvent(new Event('resize')));await expect(reopened.locator('svg')).toHaveCount(0);await page.evaluate(()=>{const w=(window as any).projectionDemo;w.maps[0]={...w.maps[0],visibility:'private'};w.releaseList();});await expect(reopened.locator('svg')).toHaveCount(0);await expect(page.getByRole('status')).toContainText('withdrawn');await page.evaluate(()=>{const d=(window as any).projectionDemo.display;for(const squarePixels of [NaN,Infinity,0,513])d.calibration({kind:'start',squarePixels});});expect((await state(page)).squarePixels).toBe(64);
});
test('calibration square wins over pending Handout rendering and transient map reads retain verified frame',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));const display=await setup(page);await page.evaluate(async()=>{const w=(window as any).projectionDemo;const file=new File([await w.content.openMapBackground()], 'background.png',{type:'image/png'});const saved=await w.data.content.upload({title:'Handout render race',file,requestId:crypto.randomUUID()});const revealed=await w.data.content.change({id:saved.id,expectedVersion:1,requestId:crypto.randomUUID(),command:{kind:'reveal'}});w.content.list=w.data.content.list;const original=w.data.content.open;w.content.open=async(...args:any[])=>{await new Promise(resolve=>w.releaseHandout=resolve);return original(...args);};w.pending=w.display.present(revealed.item);});await expect.poll(()=>page.evaluate(()=>!!(window as any).projectionDemo.releaseHandout)).toBe(true);
 await page.evaluate(async()=>{const w=(window as any).projectionDemo;w.display.calibration({kind:'start',squarePixels:88});w.releaseHandout();await w.pending;});await expect(display.getByLabel('Physical calibration test square')).toBeVisible();await expect(display.locator('canvas')).toHaveCount(0);
 await page.getByRole('button',{name:'Confirm measured square'}).click();await page.getByRole('button',{name:'Demo saved map 1',exact:true}).click();await expect(display.locator('svg')).toHaveAttribute('data-square-pixels','88');await page.evaluate(()=>{const w=(window as any).projectionDemo;w.originalList=w.content.listMaps;w.originalLoad=w.content.loadMap;w.content.loadMap=async()=>{throw new Error('Transient protected read interruption');};w.display.viewport({zoom:1,x:50,y:0});w.content.listMaps=async()=>{throw new Error('Transient transport interruption');};window.dispatchEvent(new Event('drowned-compass-content-changed'));});await expect(page.getByRole('status')).toContainText('Connection interrupted');await expect(display.getByLabel('Saved Grid Map on Party Display')).toBeVisible();await page.evaluate(()=>{const w=(window as any).projectionDemo;w.content.listMaps=w.originalList;w.content.loadMap=w.originalLoad;window.dispatchEvent(new Event('drowned-compass-content-changed'));});await expect(display.locator('svg')).toHaveAttribute('data-square-pixels','88');expect(errors).toEqual([]);
});
