import {test,expect,type Page} from '@playwright/test';
import {png} from './handout-fixtures';
const prefix=process.env.MAP_FIXTURE_PREFIX??'Ticket06 local';
async function enter(page:Page){await page.goto('./');await page.getByRole('button',{name:/^Dungeon Master /}).click();await page.getByLabel('Shared password').fill('dm-password');await page.getByRole('button',{name:'Enter the Party'}).click();}
async function mountLive(page:Page){
 await page.goto('./');await page.evaluate(async({url,key,jwt})=>{
  const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const auth=sdk.createClient(url,key);const session=await auth.auth.setSession({access_token:jwt,refresh_token:'local-verification-refresh'});if(session.error)throw session.error;
  const data=(await import('/the-drowned-compass/src/data/supabase-party-data.ts')).createSupabasePartyData(url,key);
  const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js');const renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js');const App=(await import('/the-drowned-compass/src/App.tsx')).App;
  document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:data}));
 },{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,jwt:process.env.MAP_LIVE_DM_JWT!});
 await expect(page.getByRole('button',{name:'Grid Map editor',exact:true})).toBeVisible();
}
for(const adapter of ['local','supabase'] as const)test(`${adapter}: content saves complete map intent, retries safely, conflicts, and denies private access`,async({page})=>{
 test.skip(adapter==='supabase'&&!process.env.MAP_LIVE_URL,'Needs disposable local backend fixture.');await page.goto('./');
 const result=await page.evaluate(async({image,adapter,url,key,dmJwt,playerJwt,prefix})=>{
  let jwt=dmJwt;let content,signIn,rawClient;
  if(adapter==='local'){const data=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();content=data.content;signIn=(role:'player'|'dungeon-master')=>data.signIn(role,role==='player'?'player-password':'dm-password');}
  else {const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});rawClient=client;content=(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent(client);signIn=async(role:string)=>{jwt=role==='player'?playerJwt:dmJwt;};}
  await signIn('dungeon-master');const domain=await import('/the-drowned-compass/src/domain/grid-map.ts');const editor=domain.createGridMapEditor({columns:8,rows:6,feetPerSquare:10});
  editor.draw('wall',[{x:1,y:1},{x:4,y:1},{x:4,y:4},{x:1,y:4},{x:1,y:1}]);editor.draw('door',[{x:2.5,y:1}]);for(const [i,tool]of ['floor','water','difficult'].entries())editor.draw(tool,[{x:1.5+i,y:2.5}]);
  const file=new File([new Uint8Array(image)],'art.png',{type:'image/png'});
  const input={id:crypto.randomUUID(),requestId:crypto.randomUUID(),expectedVersion:0,title:prefix+' adapter '+adapter,document:editor.snapshot().document,background:file};
  const first=await content.saveMap(input);if(!first.ok)throw new Error('Create conflicted');const original=await content.loadMap(input.id);const retry=await content.saveMap(input);
  let reused=0;for(const changed of [{...input,title:prefix+' altered'},{...input,id:crypto.randomUUID()},{...input,document:domain.createGridMapEditor().snapshot().document},{...input,background:null}])try{await content.saveMap(changed);}catch{reused++;}
  let invalid=false;try{await content.saveMap({...input,expectedVersion:1,requestId:crypto.randomUUID(),background:new File(['bad'],'bad.png',{type:'image/png'})});}catch{invalid=true;}
  const retained=await content.loadMap(input.id);const bytes=(await content.openMapBackground(input.id,1)).size;
  editor.draw('water',[{x:.5,y:.5}]);const uncommitted=await content.loadMap(input.id);const unsavedAbsent=uncommitted.document.terrain.length===3;
  const nextInput={...input,expectedVersion:1,requestId:crypto.randomUUID(),document:editor.snapshot().document,background:undefined};const next=await content.saveMap(nextInput);const stale=await content.saveMap({...nextInput,requestId:crypto.randomUUID()});
  const replacement=await content.saveMap({...nextInput,expectedVersion:2,requestId:crypto.randomUUID(),background:file});const loaded=await content.loadMap(input.id);const late=await content.saveMap(input);
  let oldDenied=false;try{await content.openMapBackground(input.id,1);}catch{oldDenied=true;}
  const rawRow=rawClient?(await rawClient.from('party_grid_maps').select('party_id,background').eq('id',input.id).single()).data:null;
  await signIn('player');const rawDenied=rawClient?Boolean((await rawClient.storage.from('party-handouts').download(`${rawRow.party_id}/${rawRow.background.object_id}`)).error)&&!(await rawClient.from('party_grid_maps').select('id').eq('id',input.id).maybeSingle()).data:true;
  let anonymousDenied=true;
  if(rawClient){const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const anonymous=sdk.createClient(url,key,{auth:{persistSession:false}});const path=`${rawRow.party_id}/${rawRow.background.object_id}`;anonymousDenied=!!(await anonymous.storage.from('party-handouts').download(path)).error&&!!(await anonymous.from('party_grid_maps').select('id').eq('id',input.id)).error&&!!(await rawClient.storage.from('party-handouts').createSignedUrl(path,30)).error;const publicResponse=await fetch(url+'/storage/v1/object/public/party-handouts/'+path);anonymousDenied=anonymousDenied&&!publicResponse.ok;}
  const list=await content.listMaps();let denied=0;for(const operation of [()=>content.loadMap(input.id),()=>content.openMapBackground(input.id,loaded.version),()=>content.saveMap({...nextInput,expectedVersion:0,requestId:crypto.randomUUID()})])try{await operation();}catch{denied++;}
  await signIn('dungeon-master');const removed=await content.saveMap({...nextInput,expectedVersion:3,requestId:crypto.randomUUID(),background:null});const after=await content.loadMap(input.id);
  return {version:first.item.version,retryVersion:retry.item.version,reused,invalid,preserved:retained.version===1&&retained.background!==null,bytes,unsavedAbsent,nextVersion:next.item.version,stale:stale.ok,replacementVersion:replacement.item.version,document:loaded.document,expected:editor.snapshot().document,rawDenied,anonymousDenied,placementStable:JSON.stringify(original.background)===JSON.stringify(loaded.background),lateVersion:late.item.version,currentVersion:loaded.version,oldDenied,playerListed:list.some(item=>item.id===input.id),denied,removed:removed.ok&&after.background===null,handoutListed:(await content.list()).some(item=>item.id===input.id)};
 },{image:Array.from(png),adapter,url:process.env.MAP_LIVE_URL??'',key:process.env.MAP_LIVE_KEY??'',dmJwt:process.env.MAP_LIVE_DM_JWT??'',playerJwt:process.env.MAP_LIVE_PLAYER_JWT??'',prefix});
 expect(result).toMatchObject({version:1,retryVersion:1,reused:4,invalid:true,preserved:true,bytes:png.length,unsavedAbsent:true,nextVersion:2,stale:false,replacementVersion:3,rawDenied:true,anonymousDenied:true,placementStable:true,lateVersion:1,currentVersion:3,oldDenied:true,playerListed:false,denied:3,removed:true,handoutListed:false});expect(result.document).toEqual(result.expected);
});
for(const adapter of ['local','supabase'] as const)test(`${adapter}: upload artwork, draw, save and reload private map on laptop/phone`,async({page},info)=>{
 test.skip(adapter==='supabase'&&!process.env.MAP_LIVE_URL,'Needs disposable local backend fixture.');if(adapter==='local')await enter(page);else await mountLive(page);
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();
 await page.getByLabel('Columns',{exact:true}).fill('8');await page.getByLabel('Rows',{exact:true}).fill('6');await page.getByRole('button',{name:'Create blank map'}).click();const title=prefix+' journey '+adapter+' '+info.project.name;await page.getByLabel('Map title').fill(title);
 // Non-square art proves proportions and logical placement, rather than just square fixtures.
 const landscape=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=800;canvas.height=400;const c=canvas.getContext('2d')!;c.fillStyle='#539476';c.fillRect(0,0,800,400);c.fillStyle='#36587b';c.fillRect(250,0,180,400);return Array.from(new Uint8Array(await(await new Promise<Blob>(resolve=>canvas.toBlob(blob=>resolve(blob!),'image/png'))).arrayBuffer()));});
 await page.getByLabel('Map Background',{exact:true}).setInputFiles({name:'landscape.png',mimeType:'image/png',buffer:Buffer.from(landscape)});await expect(page.locator('svg image')).toHaveAttribute('width','8');await expect(page.locator('svg image')).toHaveAttribute('height','4');await expect(page.locator('svg image')).toHaveAttribute('y','1');
 const grid=page.getByRole('application',{name:'Grid Map drawing surface'});await page.getByRole('button',{name:'Water',exact:true}).click();await grid.focus();await grid.press('Enter');await expect(page.locator('[data-terrain=water]')).toHaveCount(1);await page.getByRole('button',{name:'Wall',exact:true}).click();await grid.press('ArrowRight');await grid.press('Enter');await expect(page.locator('[data-edge=wall]')).toHaveCount(1);
 await page.getByLabel('View zoom').selectOption('.5');await expect(page.locator('svg image')).toHaveAttribute('height','4');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toBeVisible();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('[data-edge=wall]')).toHaveCount(0);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('[data-edge=wall]')).toHaveCount(1);
 await page.getByRole('button',{name:'Difficult terrain',exact:true}).click();await grid.press('Enter');await expect(page.getByRole('status').filter({hasText:'Unsaved changes'})).toBeVisible();
 await page.getByRole('button',{name:'Open Dungeon Master Library'}).click();await expect(page.getByRole('button',{name:new RegExp(title+' Private Grid Map')})).toBeVisible();await page.reload();if(adapter==='supabase')await mountLive(page);await page.getByRole('button',{name:'Dungeon Master Library',exact:true}).click();await page.getByRole('button',{name:new RegExp(title+' Private Grid Map')}).click();await expect(page.getByLabel('Map title')).toHaveValue(title);await expect(page.locator('[data-terrain=water]')).toHaveCount(1);await expect(page.locator('[data-terrain=difficult]')).toHaveCount(0);await expect(page.locator('[data-edge=wall]')).toHaveCount(1);await expect(page.locator('svg image')).toHaveAttribute('x','0');await expect(page.locator('svg image')).toHaveAttribute('y','1');await expect(page.locator('svg image')).toHaveAttribute('width','8');await expect(page.locator('svg image')).toHaveAttribute('height','4');
 await page.getByLabel('View zoom').selectOption('2');await expect(page.locator('svg image')).toHaveAttribute('width','8');await page.screenshot({path:`/private/tmp/ticket06-implementer-${adapter}-${info.project.name}.png`,fullPage:true});expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Remove background'}).click();await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toBeVisible();await page.getByRole('button',{name:'Reload saved map (discard draft)'}).click();await expect(page.locator('svg image')).toHaveCount(0);
});
test('editor retains draft and request identity after ambiguous response, requires explicit reload on conflict',async({page})=>{
 await page.goto('./');await page.evaluate(async()=>{
  const data=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();await data.signIn('dungeon-master','dm-password');const original=data.content;let lose=true;const content={...original,saveMap:async(input)=>{const result=await original.saveMap(input);if(lose){lose=false;throw new Error('Simulated lost accepted response');}return result;}};
  Object.assign(window,{mapData:original});const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js');const renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js');const App=(await import('/the-drowned-compass/src/App.tsx')).App;document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:{...data,content}}));
 });await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();await page.getByLabel('Map title').fill('Ambiguous map');const grid=page.getByRole('application',{name:'Grid Map drawing surface'});await page.getByRole('button',{name:'Water',exact:true}).click();await grid.press('Enter');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('alert')).toContainText('draft is retained');await expect(page.locator('[data-terrain=water]')).toHaveCount(1);await page.getByRole('button',{name:'Retry save'}).click();await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toContainText('version 1');
 await page.evaluate(async()=>{const content=(window as unknown as {mapData:import('../src/domain/party-content').PartyContent}).mapData;const item=(await content.listMaps())[0];await content.saveMap({id:item.id,expectedVersion:item.version,requestId:crypto.randomUUID(),title:item.title,document:item.document});});
 await grid.press('ArrowRight');await grid.press('Enter');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('alert')).toContainText('changed elsewhere');await expect(page.locator('[data-terrain=water]')).toHaveCount(2);await expect(page.getByRole('button',{name:'Save private Grid Map'})).toBeDisabled();await page.getByRole('button',{name:'Reload saved map (discard draft)'}).click();await expect(page.getByRole('status').filter({hasText:'Loaded saved map'})).toContainText('version 2');await expect(page.locator('[data-terrain=water]')).toHaveCount(1);
});
test('genuine Supabase ambiguous image replacement recovers receipt, preserves current bytes, and cleans obsolete image',async({page},info)=>{
 test.skip(!process.env.MAP_LIVE_URL,'Needs disposable local backend fixture.');await mountLive(page);await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();const title=prefix+' ambiguous '+info.project.name;await page.getByLabel('Map title').fill(title);await page.getByLabel('Map Background',{exact:true}).setInputFiles({name:'first.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toContainText('version 1');
 async function current(){return page.evaluate(async({url,key,jwt,title})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const result=await client.from('party_grid_maps').select('id,party_id,background,version').eq('title',title).single();if(result.error)throw result.error;return result.data;},{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,jwt:process.env.MAP_LIVE_DM_JWT!,title});}
 const initial=await current();let lose=true,block=false;
 await page.route('**/rest/v1/rpc/save_party_grid_map',async route=>{const response=await route.fetch();if(lose){lose=false;block=true;await route.fulfill({status:400,json:{message:'Simulated lost commit response'}});}else await route.fulfill({response});});
 await page.route('**/rest/v1/party_grid_map_requests?**',async route=>{if(block)await route.fulfill({status:400,json:{message:'Simulated unavailable receipt'}});else await route.continue();});
 await page.getByLabel('Map Background',{exact:true}).setInputFiles({name:'replacement.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('alert')).toContainText('draft is retained');await expect(page.locator('svg image')).toHaveCount(1);const committed=await current();expect(committed.version).toBe(2);expect(committed.background.object_id).not.toBe(initial.background.object_id);block=false;
 await page.getByRole('button',{name:'Retry save'}).click();await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toContainText('version 2');expect((await current()).version).toBe(2);
 const bytes=await page.evaluate(async({url,key,jwt,old,current})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const oldBlob=await client.storage.from('party-handouts').download(old),currentBlob=await client.storage.from('party-handouts').download(current);await client.storage.from('party-handouts').remove([current]);const preserved=await client.storage.from('party-handouts').download(current);return {oldGone:!!oldBlob.error,size:currentBlob.data?.size,preserved:!!preserved.data};},{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,jwt:process.env.MAP_LIVE_DM_JWT!,old:`${initial.party_id}/${initial.background.object_id}`,current:`${committed.party_id}/${committed.background.object_id}`});expect(bytes).toEqual({oldGone:true,size:png.length,preserved:true});
});
test('pending save cannot overwrite another loaded map or accept drawing input',async({page})=>{
 await page.goto('./');await page.evaluate(async()=>{
  const data=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();await data.signIn('dungeon-master','dm-password');const domain=await import('/the-drowned-compass/src/domain/grid-map.ts');await data.content.saveMap({id:crypto.randomUUID(),requestId:crypto.randomUUID(),expectedVersion:0,title:'Other saved map',document:domain.createGridMapEditor({columns:4,rows:4}).snapshot().document});
  const original=data.content;const content={...original,saveMap:async(input)=>{const result=await original.saveMap(input);await new Promise<void>(resolve=>Object.assign(window,{releaseSave:resolve}));return result;}};
  const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js');const renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js');const App=(await import('/the-drowned-compass/src/App.tsx')).App;document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:{...data,content}}));
 });await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();await page.getByLabel('Map title').fill('Pending map');const grid=page.getByRole('application',{name:'Grid Map drawing surface'});await page.getByRole('button',{name:'Water',exact:true}).click();await grid.press('Enter');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByLabel('Map title')).toBeDisabled();await grid.press('ArrowRight');await grid.press('Enter');await expect(page.locator('[data-terrain=water]')).toHaveCount(1);
 await page.getByRole('button',{name:'Dungeon Master Library',exact:true}).click();await page.getByRole('button',{name:/Other saved map Private Grid Map/}).click();await expect(page.getByLabel('Map title')).toHaveValue('Other saved map');await expect(page.getByRole('status').filter({hasText:'game feet per square'})).toContainText('4 × 4');await page.evaluate(()=>(window as unknown as {releaseSave:()=>void}).releaseSave());await expect(page.getByLabel('Map title')).toHaveValue('Other saved map');await expect(page.locator('[data-terrain]')).toHaveCount(0);await grid.press('Enter');await expect(page.locator('[data-terrain]')).toHaveCount(1);
});
test('genuine revealed saved fixture stays distinct from DM unsaved edits and labels shared saves accurately',async({page},info)=>{
 test.skip(!process.env.MAP_LIVE_URL,'Needs disposable local backend fixture.');await page.goto('./');const result=await page.evaluate(async({url,key,dmJwt,playerJwt,id,pointX})=>{
  const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');let jwt=playerJwt;const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const content=(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent(client);const item=await content.loadMap(id),bytes=(await content.openMapBackground(id,item.version)).size;
  const domain=await import('/the-drowned-compass/src/domain/grid-map.ts');const editor=domain.createGridMapEditor(item.document);editor.draw('water',[{x:pointX,y:.5}]);const localChanged=JSON.stringify(editor.snapshot().document)!==JSON.stringify(item.document);const unchanged=JSON.stringify((await content.loadMap(id)).document)===JSON.stringify(item.document);let denied=false;try{await content.saveMap({id,requestId:crypto.randomUUID(),expectedVersion:item.version,title:item.title,document:editor.snapshot().document});}catch{denied=true;}
  jwt=dmJwt;const accepted=await content.saveMap({id,requestId:crypto.randomUUID(),expectedVersion:item.version,title:item.title,document:editor.snapshot().document});editor.draw('difficult',[{x:2.5,y:.5}]);jwt=playerJwt;const delivered=await content.loadMap(id);return{bytes,localChanged,unchanged,denied,visibility:accepted.item.visibility,deliveredWater:delivered.document.terrain.some(cell=>cell.kind==='water'),unsavedDifficult:delivered.document.terrain.some(cell=>cell.kind==='difficult')};
 },{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,dmJwt:process.env.MAP_LIVE_DM_JWT!,playerJwt:process.env.MAP_LIVE_PLAYER_JWT!,id:process.env.MAP_LIVE_REVEALED_ID!,pointX:info.project.name.startsWith('phone')?3.5:.5});expect(result).toEqual({bytes:png.length,localChanged:true,unchanged:true,denied:true,visibility:'revealed',deliveredWater:true,unsavedDifficult:false});
 await mountLive(page);await page.getByRole('button',{name:'Dungeon Master Library',exact:true}).click();await page.getByRole('button',{name:new RegExp(prefix+' revealed fixture Revealed Grid Map')}).click();await expect(page.getByRole('status').filter({hasText:'Loaded saved map'})).toContainText('Revealed');await page.getByRole('button',{name:'Save for everyone',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Saved for everyone'})).toContainText('Revealed');
});
test('genuine background open rejects a concurrent accepted replacement after bytes download',async({page})=>{
 test.skip(!process.env.MAP_LIVE_URL,'Needs disposable local backend fixture.');await page.goto('./');const saved=await page.evaluate(async({url,key,jwt,image,title})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const content=(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent(client);const domain=await import('/the-drowned-compass/src/domain/grid-map.ts');const result=await content.saveMap({id:crypto.randomUUID(),requestId:crypto.randomUUID(),expectedVersion:0,title,document:domain.createGridMapEditor().snapshot().document,background:new File([new Uint8Array(image)],'race.png',{type:'image/png'})});return result.item;},{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,jwt:process.env.MAP_LIVE_DM_JWT!,image:Array.from(png),title:prefix+' open race'});
 let raced=false;await page.route('**/storage/v1/object/party-handouts/**',async route=>{const response=await route.fetch();if(!raced){raced=true;const changed=await fetch(process.env.MAP_LIVE_URL!+'/rest/v1/rpc/save_party_grid_map',{method:'POST',headers:{apikey:process.env.MAP_LIVE_KEY!,authorization:'Bearer '+process.env.MAP_LIVE_DM_JWT!,'content-type':'application/json'},body:JSON.stringify({p_id:saved.id,p_request_id:crypto.randomUUID(),p_expected_version:saved.version,p_title:saved.title,p_document:saved.document,p_mode:'remove',p_background:null,p_client_signature:'fixture race removal'})});if(!changed.ok)throw new Error('Fixture concurrent removal failed');}await route.fulfill({response});});
 const denied=await page.evaluate(async({url,key,jwt,id,version})=>{const sdk=await import('/the-drowned-compass/node_modules/.vite/deps/@supabase_supabase-js.js');const client=sdk.createClient(url,key,{accessToken:async()=>jwt});const content=(await import('/the-drowned-compass/src/data/supabase-party-content.ts')).supabasePartyContent(client);try{await content.openMapBackground(id,version);return false;}catch{return true;}},{url:process.env.MAP_LIVE_URL!,key:process.env.MAP_LIVE_KEY!,jwt:process.env.MAP_LIVE_DM_JWT!,id:saved.id,version:saved.version});expect(raced).toBe(true);expect(denied).toBe(true);
});
test('accepted receipt retry reloads current version after confirmation read fails',async({page})=>{
 await page.goto('./');await page.evaluate(async()=>{
  const data=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();await data.signIn('dungeon-master','dm-password');const original=data.content;let fail=true;const content={...original,loadMap:async(id:string)=>{if(fail){fail=false;throw new Error('Simulated unavailable confirmation read');}return original.loadMap(id);}};Object.assign(window,{mapData:original});
  const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js');const renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js');const App=(await import('/the-drowned-compass/src/App.tsx')).App;document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:{...data,content}}));
 });await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();await page.getByLabel('Map title').fill('Original accepted map');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('alert')).toContainText('draft is retained');await expect(page.getByLabel('Map title')).toHaveValue('Original accepted map');
 await page.evaluate(async()=>{const content=(window as unknown as {mapData:import('../src/domain/party-content').PartyContent}).mapData;const item=(await content.listMaps())[0];await content.saveMap({id:item.id,expectedVersion:item.version,requestId:crypto.randomUUID(),title:'Current accepted map',document:item.document});});await page.getByRole('button',{name:'Retry save'}).click();await expect(page.getByLabel('Map title')).toHaveValue('Current accepted map');await expect(page.getByRole('status').filter({hasText:'Saved privately'})).toContainText('version 2');
});
test('uncertain new-map create followed by a new edit can resolve conflict by reloading accepted map',async({page})=>{
 await page.goto('./');await page.evaluate(async()=>{
  const data=(await import('/the-drowned-compass/src/data/in-memory-party-data.ts')).createInMemoryPartyData();await data.signIn('dungeon-master','dm-password');const original=data.content;let fail=true;const content={...original,saveMap:async(input)=>{const accepted=await original.saveMap(input);if(fail){fail=false;throw new Error('Simulated uncertain create');}return accepted;}};
  const React=await import('/the-drowned-compass/node_modules/.vite/deps/react.js');const renderer=await import('/the-drowned-compass/node_modules/.vite/deps/react-dom_client.js');const App=(await import('/the-drowned-compass/src/App.tsx')).App;document.getElementById('root')!.remove();const root=document.createElement('div');document.body.append(root);(renderer.createRoot??renderer.default.createRoot)(root).render((React.createElement??React.default.createElement)(App,{partyData:{...data,content}}));
 });await page.getByRole('button',{name:'Grid Map editor',exact:true}).click();await page.getByLabel('Map title').fill('First accepted title');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('alert')).toContainText('draft is retained');await page.getByLabel('Map title').fill('New unaccepted title');await page.getByRole('button',{name:'Save private Grid Map'}).click();await expect(page.getByRole('alert')).toContainText('changed elsewhere');await expect(page.getByLabel('Map title')).toHaveValue('New unaccepted title');await page.getByRole('button',{name:'Reload saved map (discard draft)'}).click();await expect(page.getByLabel('Map title')).toHaveValue('First accepted title');await expect(page.getByRole('status').filter({hasText:'Loaded saved map'})).toContainText('version 1');
});
