import {readFile,writeFile,mkdir} from 'node:fs/promises';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {decodePng,encodePng} from '../png.mjs';import {verify as reference} from '../magick/verify.mjs';
const dir=new URL('../../provider-evidence/verifier-'+Date.now()+'/',import.meta.url);await mkdir(dir,{recursive:true});
const name=process.argv[2]??'map-browser-verifier-03-staged',results=[],manifest=JSON.parse(await readFile(new URL('fixtures/manifest.json',import.meta.url)));
const send=async(label,id,bytes,expected,extra={},stage='verify')=>{const start=performance.now();try{const response=await fetch('http://127.0.0.1:4196/'+stage,{method:'POST',headers:{'X-Probe-Request':id,'Content-Type':'image/png',...extra},...(bytes?{body:bytes}:{}),signal:AbortSignal.timeout(10000)});const result={label,status:response.status,wallMs:performance.now()-start,response:await response.json(),expected};result.matchesExpected=result.response.kind===expected;results.push(result);console.log(JSON.stringify(result));}catch(error){results.push({label,error:String(error),expected,matchesExpected:false});}};
for(let repeat=0;repeat<2;repeat++)for(const id of ['live','transparent','lowalpha','noise']){
 const read=kind=>readFile(new URL('fixtures/'+id+'-'+kind+'.png',import.meta.url)),source=await read('source'),candidate=await read('candidate'),output=await read('output');const proof=reference(source,candidate,output);if(!proof.exact)throw Error('Independent reference failed');await send(id+' prepare cold '+repeat,id,null,'prepared',{},'prepare');await send(id+' finalize cold '+repeat,id,output,'verified');
}
const live=await readFile(new URL('fixtures/live-output.png',import.meta.url));
for(const [label,index]of [['outside tamper',0],['inside tamper',(160*1024+650)*4]]){const d=decodePng(live);d.rgba[index]^=1;await send(label,'live',encodePng(d),'rejected');}
await send('wrong request binding','noise',live,'rejected');await send('unknown request','missing',live,'rejected');
await send('client authority assertions rejected','live',live,'rejected',{'X-Probe-Parent':'forged-parent','X-Probe-Region':'0,0,1024,1024','X-Probe-Source':'forged','X-Internal-Proof':'forged'});
await send('corrupt PNG','live',Buffer.from('not PNG'),'rejected');
const execute=promisify(execFile);for(const [file,args]of [['events.log',['logs',name]],['cgroup.txt',['exec',name,'sh','-c','cat /sys/fs/cgroup/memory.peak /sys/fs/cgroup/memory.max /sys/fs/cgroup/cpu.max']]]){try{const r=await execute('docker',args,{timeout:5000,killSignal:'SIGKILL',maxBuffer:8*1024*1024});await writeFile(new URL(file,dir),r.stdout+r.stderr);}catch(error){await writeFile(new URL(file,dir),String(error));}}
await writeFile(new URL('report.json',dir),JSON.stringify({sourceHead:'staged pre-freeze source; final SHA recorded separately',browserSourceHead:'fe48909b478971bc6e6250a6ed19ece41fd1e2ef',manifest,policy:'oneshot; every prepare/finalize stage fresh user worker; no warm claim',results},null,2));const joins={};for(const line of (await readFile(new URL('events.log',dir),'utf8')).split('\n')){try{const event=JSON.parse(line),executionId=event.metadata?.execution_id;if(!executionId)continue;const record=joins[executionId]??={executionId};if(event.event_type==='Log'){try{Object.assign(record,JSON.parse(event.event.msg));}catch{}}if(event.event_type==='Shutdown')Object.assign(record,{reason:event.event.reason,cpuMs:event.event.cpu_time_used,memorySampleBytes:event.event.memory_used.total});}catch{}}const joined=results.map(result=>({...result,runtime:Object.values(joins).find(event=>event.workerInstance===result.response?.workerInstance)}));await writeFile(new URL('joined.json',dir),JSON.stringify(joined,null,2));console.log('Evidence '+dir.pathname);if(results.some(r=>!r.matchesExpected))process.exitCode=1;
