import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {prepareExpected,finalizeExpected,digest} from './decoder.mjs';import {decodePng,encodePng} from '../png.mjs';import {verify as independent} from '../magick/verify.mjs';
const root=new URL('./fixtures/',import.meta.url),manifest=JSON.parse(await readFile(new URL('manifest.json',root)));const cases={};
for(const id of Object.keys(manifest)){const read=k=>readFile(new URL(id+'-'+k+'.png',root));cases[id]={source:await read('source'),candidate:await read('candidate'),output:await read('output')};}
for(const id of Object.keys(cases))test(id+' server-prepared digest independently exact',async()=>{const d=cases[id],proof=await prepareExpected(manifest[id],id,d.source,d.candidate);assert.equal(independent(d.source,d.candidate,d.output).exact,true);assert.equal(proof.expectedRgbaDigest,await digest(decodePng(d.output).rgba));assert.equal((await finalizeExpected(manifest[id],id,proof,d.output)).kind,'verified');});
const d=cases.live,b=manifest.live,proof=await prepareExpected(b,'live',d.source,d.candidate);
for(const [name,index]of [['outside',0],['inside',(160*1024+650)*4]])test(name+' hash rejects altered channel',async()=>{const image=decodePng(d.output);image.rgba[index]^=1;assert.equal((await finalizeExpected(b,'live',proof,encodePng(image))).kind,'rejected');});
for(const [name,alter]of [['parent',{parentId:'wrong'}],['request',{requestId:'noise'}],['source',{sourceDigest:'0'.repeat(64)}],['candidate',{candidateDigest:'0'.repeat(64)}],['region',{region:{...b.region,x:1}}],['expired',{expiresAt:0}]])test(name+' prepared binding rejects',()=>assert.rejects(()=>finalizeExpected(b,'live',{...proof,...alter},d.output)));

for(const kind of ['source','candidate'])test('same-size prepare '+kind+' substitution rejects',()=>{const t=cases.transparent;return assert.rejects(()=>prepareExpected(manifest.transparent,'transparent',kind==='source'?t.candidate:t.source,kind==='candidate'?t.source:t.candidate));});
